anmode/grabtern-frontend

components/Banner.js, components/Course.js, package-lock.json, package.json, pages/_app.page.js, pages/_document.page.js, pages/index.page.js, styles/globals.css
**Fix errors & commented the js script link file & create my own & fix some issues & styles**
=> fix: errors, issues & styles

components/Course.js, next.config.js, package-lock.json, package.json, pages/_app.page.js, pages/_document.page.js, pages/index.page.js, styles/globals.css
**What I've changes**
1. Fix the loader issue because the loader maybe can't be see but the loader cover the whole screen because all of the button & anchor does not work
2. Fix the slider not working
3. Add jQuery & fix the jQuery issues
4. Improvements on styles
=> fix: all issues, bug and styles

.eslintrc.json, components/SimpleBanner.js, pages/about.page.js, pages/login.page.js, pages/register.page.js
convert login, register and about site to next js
=> convert other site to next js

components/Banner.js, components/Course.js
=> Added link

pages/login.page.js, public/assets/css/style.css
Closes: #132 
Applied changes in CSS.
=> [BUG] fixed issue #132

package.json, pages/refundandcancellation.page.js
=> Fixed : issue #165

.github/workflows/greetings.yml, components/mentor.js, public/assets/css/style.css, styles/globals.css
Change UI also Responsive the Mentor & Contact us page for all devices #161 
[Grabtern responsive mentor page.webm](https://github.com/anmode/grabtern-frontend/assets/106610322/61e20fb3-2d24-445b-a211-7761411b0fb7)
=> Responsive the Mentor & Contact us page for all devices

components/Footer.js, components/Header.js, styles/LoginDropdown.module.css
#120 
Added hovering effect on navbar tabs 
original:
updated:
=> Adding Hover effect

README.md
Closes: #138 
I have done changes in readme section of the file.
For example:
- Added a new function to handle XYZ.
- Updated the ABC module to fix the bug.
- Refactored code in the DEF class for improved performance.
-->
| ![Original screenshot](link) | <img width="392" alt="Screenshot 2023-05-29 at 10 41 21 PM" src="https://github.com/anmode/grabtern-frontend/assets/105661636/4377aaa3-aba9-48ca-bf89-73d04ad2a6bf">
=> Tech Stack Section Added

.gitignore, components/Header.js, pages/forgotpass.page.js, pages/login.page.js, pages/register.page.js, public/assets/css/style.css, public/sitemap-0.xml, styles/LoginDropdown.module.css, styles/globals.css
- I have fixed the height of navbar which was causing the navbar to appear thick and also it was covering the content
- I have changed the positioning of the main form in user login page 
- In the Orignal screenshot 2 you can clearly see how bad it looks
| ![](https://github.com/arpittyagirocks/Media/blob/main/before1.png?raw=true) | ![link](https://github.com/arpittyagirocks/Media/blob/main/after1.png?raw=true) |
| ![](https://github.com/arpittyagirocks/Media/blob/main/before2.png?raw=true) | ![link](https://github.com/arpittyagirocks/Media/blob/main/after2.png?raw=true) |
=> Fixed the Navbar height and user login page

styles/globals.css
Hi @anmode, 
As discussed, I have fixed the UI, which got affected due to the css changes (styles/globals.css) as part of below issue, got applied at global level, thatswhy Home page also got affected.
https://github.com/anmode/grabtern-frontend/commit/f3fe039452f4f53297b627d49f790586e493c53b
I have fixed it now as part of my issue #217 . But the card layout of Mentor page will be back to its previous state.  If required please work with Ilma Salsabil, to apply her new layout changes only to the Mentor page.
Kindly review the changes and accept it.
Thanks
=> Fixed the broken UI as part of the defect(#217)

components/About.js, pages/index.page.js
Related to issue-196
Made minor improvisations to help in enhancements
1. Changed 'What Grabtern Do for their Students' to 'What Grabtern Does For It's Students?
2. Changed 'Why to be Mentor at Grabtern?' to 'Why Mentor At Grabtern?'
Closes: #196 
Kindly review this.
=> Made the enhancements related to issue-196

pages/mentors.page.js
Closes: #282
I have fixed the heading in Mentors page in two ways:
- here's -> here
- Capitalized the first letter of each word (since it's a heading)
| ![Screenshot 2023-06-07 215912](https://github.com/anmode/grabtern-frontend/assets/89148144/54f43a51-924e-49ca-9739-dc933a1c2bfa) | ![Screenshot 2023-06-07 215948](https://github.com/anmode/grabtern-frontend/assets/89148144/0f2bf553-6941-4222-a830-2d1804118204) |
=> Fix Heading in Mentors Page

components/Internship.js
Closes: #265 
| https://github.com/anmode/grabtern-frontend/assets/105661636/65b4ef07-deb3-4b90-a242-af26ab4bfba6   |  https://github.com/anmode/grabtern-frontend/assets/105661636/9e83a4df-8171-4881-ab5e-f42108efa198  |
=> Fixed Issue #265

pages/_app.page.js, pages/_document.page.js
Closes #259 
- Add the favicon
- Removed these meta tags from `_document.page.js` due to standard conventions
```html
<meta name="title" content="GrabTern" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
```
- Add the following meta tags in `_app.page.js`
```html
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="language" content="English" />
<meta name="linkedin:profile" content="https://www.linkedin.com/company/grabtern/" />
<meta property="instagram:username" content="https://www.instagram.com/grabtern.guide/" />
<meta name="twitter:site" content="@grabtern_twitter_username" />
```
=> chore: add favicon and meta tags

styles/globals.css
=> Scrollbars removal

styles/globals.css
=> fixed space in mentor page

public/assets/css/style.css
Closes: #360 
- updated the styles to fix up the icon translate
- was done with use of margin property
| ![image](https://github.com/anmode/grabtern-frontend/assets/72339688/c654cfa9-39bd-4f00-ad57-60d9b2e09b14) | ![image](https://github.com/anmode/grabtern-frontend/assets/72339688/d3538aa7-e4cf-4f6f-9a0c-c6f5b9f070bf) |
=> fix: 🐞 [BUG] - Icon translate #360

components/About.js
Closes: #362 
- went to the code of the html video and added the `autoPlay` property on it
- now the video autoplays with ease
| ![image](https://github.com/anmode/grabtern-frontend/assets/72339688/d231f8fe-78cf-4491-9436-16ffe815d033) | ![image](https://github.com/anmode/grabtern-frontend/assets/72339688/66e1e535-ab0d-4f5a-9b51-e0744c34f1e1) |
=> feature:  To let the video just autoplay #362

styles/globals.css
Site Overflow
Closes: #332 
- [✔️] My code adheres to the established style guidelines of this project.
- [✔️] I have conducted a self-review of my code.
- [ ✔️] I have included comments in areas that may be difficult to understand.
- [ ✔️] I have made corresponding updates to the project documentation.
- [✔️ ] My changes have not introduced any new warnings.
=> OverflowRemoved

pages/contact.page.js
reference issue #371 
I've fixed the issue.
Now the form not accepting empty inputs.
and also it will get reset to initial state after we click on send.
Ps: it is also displaying "sent" message. 
in this video it is not visible.
https://github.com/anmode/grabtern-frontend/assets/71914071/50559726-1350-449c-a0f0-fec7e1d6b86d
=> fixing contact form

pages/mentors.page.js, styles/globals.css
Closes: #[#222]
| 
| 
|
Search bar can filter on basis of name, interntype and currentstatus.
=> Fixed isssue #222 added search bar

components/SimpleBanner.js, pages/contact.page.js
closes #377 
https://github.com/anmode/grabtern-frontend/assets/71914071/bd6e0901-c1bf-49a2-ae53-873975d0dbba
=> fixed Banner

components/mentorProfile/MentorCard.js
Closes: #365 
|           Original           |   
|        Updated           |
https://github.com/anmode/grabtern-frontend/assets/105661636/9974b4d4-8738-4b60-8776-dd927db999e6
) |
=> Enhanced Mentor cards

.github/workflows/codeql.yml, components/mentorProfile/MentorCard.js
Closes: #394 
Added the CodeQL workflow to be implemented on every push and pull request.
=> Add CodeQL workflow

components/About.js, styles/about.module.css, styles/globals.css
Closes: #354 
|        Updated           | : <img width="1416" alt="Screenshot 2023-06-21 at 3 08 35 AM" src="https://github.com/anmode/grabtern-frontend/assets/105661636/2bc27333-9332-4835-a48e-7dd0449e5423">
=> Resolved Conflicts in #354

package.json, pages/contact.page.js
Closes: #393
@anmode Please review it!!
=> Contact form validation checked before alert sent message issue

components/mentor.js, styles/globals.css
New mentor card has been design with new color scheme and uses tailwind css
Closes: #364 
=> Removed previous commits

components/hackthons/components/Searchbar.js, pages/hackathon.page.js, pages/index.page.js
Hello @anmode,
Now we can select multiple features at a time. Have a look: 
https://github.com/anmode/grabtern-frontend/assets/90946899/30b55234-5001-42d6-8f61-12faa5ac5b11
Closes: #464  
I changed the code of `handlechangetag` function.
=> [Feature Request] - Can Select Multiple Hackathon Tag #464

components/UI/Button/Button.module.css, components/UI/Card/IconCard.js, components/UI/Card/ImageCard.js, components/UI/Card/ProfileCard.js, components/UI/Links/Link.module.css, components/UI/Section/Section.js, components/UI/Section/SectionHeader.js, package.json, pages/components.page.js, public/assets/css/animated-headline.css, public/assets/css/style.css, styles/globals.css, tailwind.config.js
Follow up for #476 
Start adding Section Components
Start adding Card Components
=> Refactoring 2

styles/contact.module.css
=> fixed contact page in mobile width

components/homePage/Banner.js, components/layout/Header.js, components/layout/UserProfile.js
follow up for https://github.com/anmode/grabtern-frontend/issues/322#issuecomment-1638178939
1. Added profile Icon and drop down in navbar
2. Fix `be a mentor` button of banner and made it dynamic.
=> Fix User Profile icon issue of navbar

components/mentorDashboard/sidebar.js
I have created a sidebar for Mentor Dashboard as stated in issue no - #530.
Please review it!
=> Created Sidebar for Mentor Dashboard

components/mentorDashboard/calendar.js, styles/dashboard.module.css
=> [WIP]: Added schedule page

pages/_app.page.js
Closes: #501 
- This PR is about adding important meta elements for improving the site's seo score along to boost site's vital performance
- Meta elements in HTML play a crucial role in providing information about the webpage to browsers and search engines. 
- They are typically placed in the head section of an HTML document and are not displayed directly on the webpage.
- Those Meta elements in HTML serve various purposes, including defining document encoding, improving search engine visibility, enhancing social media sharing, optimizing for mobile devices, and influencing browser behavior. 
- Utilizing appropriate meta elements can significantly impact how webpages are perceived, indexed, and shared on the internet.
=> feat: add important meta elements to improve seo 🚀

pages/mentors.page.js
=> "no match found" in search query of mentors page

components/UI/Card/IconCard.js, components/homePage/About.js, components/homePage/MentorSection.js
Closes: #581 
- Revamped the design of the List and It's items on Homepage.
- Added tailwind utility classes to revamp the design properly.
<table border="2">
<tr>
<th>O R I G I N A L </th>
<th>U P D A T E D</th>
</tr>
<tr>
<td>
<table border="1">
<tr>
<th>MOBILE</th>
<th>DESKTOP</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</td>
<td>
<table border="1">
<tr>
<th>MOBILE</th>
<th>DESKTOP</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</td>
</tr>
</table>
=> revamp: list items design on homepage ✨

components/Community/CommunityCard.jsx, components/layout/Header.js, pages/community.page.js, pages/index.page.js
Closes: #540 
Moved Grabtern section to a different page called community.
- `components/layout/Header.js`
- `pages/index.page.js`
- `components/Community/CommunityCard.jsx`
- `pages/community.page.js`
[GrabTern-Grab-Your-Internship.webm](https://github.com/anmode/grabtern-frontend/assets/130365071/46f33f3c-b78b-492f-b83f-0d62a4c0aa60)
@anmode please review this PR.
Thanks
=> fix: moved community section to different page

README.md
I have added the documentation for grabtern email feature in ReadMe as stated in this issue -> #565.
=> Added grabtern email feature in ReadMe

.husky/commit-msg, CONTRIBUTING.md, commitlint.config.js, package.json
Closes: #599 
install the Commit lint into project
install the  husky 
=> feat: init Commlint✨ 

components/mentorDashboard/profile.js
Mentor Profile Page added
Closes: #532
- [ x] My code adheres to the established style guidelines of this project.
- [x ] I have conducted a self-review of my code.
=> Mentor Profile Page Added

components/AddInternship.js
Fixed the name of the file and the main function(AddInternship) in it.
=> Rename AddIntership to AddInternship

components/mentorPage/components/Company.js, components/mentorPage/components/FAQ.js, components/mentorPage/components/Testimonials.js, pages/data/faq.js, pages/data/testiomialsData.js, pages/mentor.page.js
- add:  a dynamic testimonial section to the  ``/mentor`` page.
- refactored FAQ section for better responsiveness
=> feat: testimonials section

components/mentorDashboard/profile.js, components/mentorPage/components/Testimonials.js, pages/auth/resetpassword.page.js, pages/data/faq.js, pages/mentor.page.js, styles/globals.css
Reset form was not working.
Fix the reset password form functionality
=> fixed reset password form submission and working

pages/auth/register.page.js
=> registration to register

components/layout/Footer.js, pages/auth/login.page.js, styles/form.module.css
Closes: #605 & #608
- First, We added proper label for the newsletter form which can be found on Footer with proper attributes so that the `input` and `label` would associate properly for accessibility devices.
- The `label` is visually hidden, It's only visible for accessibility devices using the `sr-only` tailwind utility class.
- Second, We fixed the incorrect case of Heading on Login page using string methods of JavaScript.
- `entityType` is the variable that holds a string, either "user" or "mentor".
- `.charAt(0)` is the method which gets the first character of the `entityType` string.
- `.toUpperCase()`  converts the first character of `entityType` to uppercase.
- `+  entityType.slice(1)` used for concatening the uppercased letter with `slice` which extracts the part of the …
=> fix: lacking label for newsletter and incorrect way of displaying heading on login page 👷🏻🛠

pages/auth/login.page.js, pages/auth/register.page.js, public/assets/Visibillity.jsx, public/assets/VisibillityOff.jsx
Closes: #[614]
- [✔️ ] My code adheres to the established style guidelines of this project.
- [✔️ ] I have conducted a self-review of my code.
- [✔️ ] I have included comments in areas that may be difficult to understand.
- [ ✔️] I have made corresponding updates to the project documentation.
- [✔️ ] My changes have not introduced any new warnings.
| ![Original screenshot](link) | ![Updated screenshot](lin
https://github.com/anmode/grabtern-frontend/assets/109091515/68fecb5e-7af2-4b40-b7e5-ddf0d58acaae
k) |
=> Fixed the confirmpassword visibility

pages/auth/forgotpass.page.js, pages/auth/login.page.js, pages/auth/register.page.js, pages/auth/resetpassword.page.js
Closes: #638
Fixes apis getting called without any input values in SignUp, SignIn, ForgotPassword and ResetPassword pages.
1. Made all input fields required
2. Disabled the button if all the inputs are empty
3. Showed not-allowed cursor
=> [Fix] - Apis getting called without any input values

components/mentorDashboard/profile.js
Connected mentor profile api in mentor profile page
=> Mentor profile api connection

components/mentorDashboard/calendar.js, components/newMentorProfile/SessionCard.js, package.json, public/sitemap-0.xml
=> added start and end time select box in schedule page

components/eventLogin/EventLogin.js, pages/auth/login.page.js, pages/auth/register.page.js, styles/form.module.css
=> fixed spinner in mobile device

components/eventLogin/EventLogin.js, pages/auth/resetpassword.page.js, styles/form.module.css
fixed reset password page in mobile width and added spinner on loading
=> feat: fixed reset password page

components/basic/MoveToTop.js
Closes: #640 
1. removed the top text in gototop button
2. added a little transition effect (opacity-0 to opacity-1)
| ![Original screenshot](link) |![Screenshot 02-08-2023 15_31_10](https://github.com/anmode/grabtern-frontend/assets/89072785/6f2d3e46-df65-4488-adf1-ce78d0bda90e)|
=> fix: removed text in top-btn

.github/workflows/Changelog.yml
=> feat: Create Changelog.yml ✨

components/mentorProfile/components/SharePageModal.js
Closes: #629 
--Added social media share APIs to share the Mentor's Profile efficiently.
| ![Original screenshot](
) | ![Updated screenshot](
) |
Video Preview:
https://github.com/anmode/grabtern-frontend/assets/100708686/705090e3-abcd-419f-9083-6d9abd2bdc9f
=> feat: add social links to share Profile. #629

components/UI/Button/button.test.js, jest.config.json, package.json
=> [Solved]: Workflow Issue

components/mentorDashboard/Bookings.js, components/mentorDashboard/home.js
Connected  mentor dashboard booking page with backend for get sessions.
=> Booking page backend connection

components/mentorDashboard/home.js, components/mentorDashboard/queries.js, components/mentorDashboard/ticketForm.js, pages/dashboard/mentor.page.js, styles/queries.module.css
- add: responsive design/optimization for mobile devices
@anmode
=> feat: responsive design and optimization for queries page in dashboard/mentor

components/mentorDashboard/sidebar.js
=> feat: fixed color of grabtern logo in mentor dashboard

components/mentorDashboard/queries.js, styles/queries.module.css
=> feat: improved queries page UI and optimized the page

styles/globals.css
=> feat: fixed button hover color

components/UI/Button/Button.js, components/hackthons/components/Searchbar.js, pages/auth/forgotpass.page.js, pages/auth/resetpassword.page.js, pages/hackathon.page.js
Closes: #706
1. **Endless Console Logging:** Removed excessive console log statements from the hackathon page code to eliminate the continuous stream of console log messages that were cluttering the browser console.
2. **useEffect Error Fix:** Refactored the implementation of the `useEffect` hook within the hackathon page. Updated the dependency array and handling of state updates to prevent the "Maximum Update Depth Exceeded" error.
=> fix: useeffects and removed annoying console logs

components/basic/SvgMaker.js, package.json, pages/auth/forgotpass.page.js, pages/auth/resetpassword.page.js, pages/hackathon.page.js, pages/internship.page.js, pages/mentor.page.js
This pull request addresses the issue of extended build times by removing Material-UI (MUI) usage from various pages, such as Mentor and ResetPassword, where it was deemed unnecessary. Additionally, I've replaced MUI icons with SVGs using a reusable SVG component to enhance the performance and streamline the codebase.
Closes: #701
**Changes Made:**
1. **MUI Removal:**
- Pages like Mentor and ResetPassword no longer rely on MUI components.
- Removed MUI-related dependencies from package.json.
- Cleaned up unused MUI styles and classes.
2. **Styling with CSS and Tailwind:**
- Replaced MUI styling with custom CSS and integrated Tailwind CSS for improved styling options.
- Adjusted layout and colors to match our design language while ensuring a consistent look across the application.
3. **SVG …
=> Removing MUI and Improving UI with SVGs

components/Community/CommunityCard.jsx, components/UI/Button/Button.js, components/basic/SvgMaker.js, components/hackthons/components/Searchbar.js, package.json, pages/auth/forgotpass.page.js, pages/blogDetail/blogDetail.page.js, pages/community.page.js, pages/hackathon.page.js, pages/internship.page.js, pages/mentor.page.js
=> Added the no. of commits and contributors title .

components/mentorDashboard/CalendarComponent/card.js, package.json
- add: optimization for mobile devices
- add: some UI changes like buttons and inputs
@anmode
=> feat: optimized Calender tab in ``dashboard/mentor/calender``

components/mentorDashboard/Payment.js
- add: card component containing info about mentor's bank/payment details
- add: submit button to submit and send the details
- add: made the card responsive
=> feat: add more features to payment page in ``dashboard/mentor/payment``

components/layout/Footer.js
Closes: #601
In this pull request, I've implemented a newsletter subscription feature connected with Hashnode on our website. Users can now submit their email addresses through the website, and upon submission, they will receive a confirmation email from Hashnode to confirm their subscription.
**Changes Made:**
1. Created a new subscription form on the website's front end to collect user email addresses.
2. Implemented backend logic using Express.js to handle form submissions and communicate with Hashnode's API.
3. Integrated the Hashnode API to send a POST request to subscribe users to the newsletter using the provided email and publication ID.
4. Configured the backend to handle Hashnode's confirmation email process, allowing users to confirm their subscription by clicking a link in the …
=> Add Hashnode Newsletter Subscription and Confirmation Email

components/layout/Footer.js, components/mentorDashboard/home.js, components/mentorDashboard/sidebar.js, pages/dashboard/mentor.page.js
- add: feature to click for expanding sidebar and collapsing it.
- remove: feature to hover for expanding sidebar
- add: button and minor optimization
Above feature is added to all the dashboard pages/components.
@anmode
=> feat: on click expand/collapse sidebar

components/mentorDashboard/sidebar.js, package.json, pages/dashboard/mentor.page.js
This PR is a part of #737 
- replaced the show/hide sidebar icons with the mui toggle switch component with functionality.
=> feat: toggle to open/close sidebar

components/UI/Button/Switch.js, components/UI/index.js, components/mentorDashboard/CalendarComponent/card.js
1. Created a new switch component 
2. Replaced mui switch component with the new one
=> Fixed MUI error in contact tab of mentor dashbord

components/userDashboard/Bookings.js
=> userBooking

styles/form.module.css, styles/globals.css, styles/userRegistration.module.css
Closes: #718
This pull request contains the updated code for the _'Sign Up' Form Input Area Improved Styling_ which includes the styling changes in the input areas of the form.
_Design is consistent on all screens._
| ![op](https://github.com/anmode/grabtern-frontend/assets/115794049/5cfbe7eb-bcf2-4a46-acd4-4e3ed9ef1e21) | ![op](https://github.com/anmode/grabtern-frontend/assets/115794049/e19e68c7-3117-43e5-a5ff-d15872290d13)|
=> [Feature Request] - 'Sign Up' Form Input Area Improved Styling

components/mentorDashboard/Payment.js, components/mentorDashboard/PaymentComponent/Form.js, styles/userRegistration.module.css
Created workflow for adding, getting and updating account details in mentor dashboard
=> Working of payment tab

components/mentorDashboard/home.js, components/mentorDashboard/profile.js, components/mentorDashboard/sessions.js, package.json, pages/dashboard/mentor.page.js
=> some fixes

components/basic/ComingSoon.js, pages/dashboard/mentor.page.js
Redesign coming soon page
Added it in dashboard where ever required
=> Coming soon page

components/mentorDashboard/Bookings.js, components/mentorDashboard/Payment.js, components/mentorDashboard/PreLoader.js, components/mentorDashboard/QueriesComponent/ticketForm.js, components/mentorDashboard/home.js, components/mentorDashboard/profile.js, components/mentorDashboard/queries.js, components/mentorDashboard/sessions.js, pages/dashboard/mentor.page.js
1. Added loading and error in dashboard page
2. Used these state in different component
=> Adding loading state in dashboard

components/basic/ImageCropper.js, components/mentorDashboard/profile.js, components/userDashboard/profile.js, pages/dashboard/mentor.page.js, pages/dashboard/user.page.js
Added profile image input in user dashboard profile tab
=> Added profile image  input in user dashboard

components/MentorRegistration/MentorFormRegistration.js, components/MentorRegistration/components/MagicUrlPopUp.js, components/basic/Overlay.js
Created form to register mentor using magic url.
=> Mentor Registration using Magic url

components/mentorDashboard/Bookings.js, components/mentorDashboard/Payment.js, components/mentorDashboard/home.js, components/mentorDashboard/profile.js, components/mentorDashboard/sessions.js, pages/auth/login.page.js, pages/blogDetail/[blogDetailId].page.js, pages/dashboard/user.page.js, styles/globals.css
=> feat: added toast.promise

components/mentorDashboard/Bookings.js, components/mentorDashboard/Payment.js, components/mentorDashboard/home.js, components/mentorDashboard/profile.js, components/mentorDashboard/sessions.js, pages/auth/login.page.js, pages/blogDetail/[blogDetailId].page.js, pages/dashboard/user.page.js, styles/globals.css
Reverts anmode/grabtern-frontend#758
=> Revert "feat: added toast.promise"

components/layout/Footer.js
Closes: #760  
Added GitHub repo link in Footer Section
=> fix: Added GitHub repo link in Footer Section
